//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.07 at 04:56:06 PM IST 
//

package com.cgi.timesheet.models.entity;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.NaturalId;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * <p>
 * Java class for contentTableType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="contentTableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="paraSeq" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fileId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "ParaType")
@Entity(name = "encontenttable")
@Table(name = "encontenttable")
@XmlAccessorType(XmlAccessType.FIELD)
public class ParaType {

	@Column(name = "contentid", unique = true, nullable = false)
	@Id
	@NotNull
	@XmlElement(required = false)
	protected int contentId;
	@XmlElement
	@Column(name = "paraseq")
	protected int paraSeq;
	@Column(name = "fileid")
	protected int fileId;
	@ManyToOne(cascade = { CascadeType.ALL, CascadeType.PERSIST,
			CascadeType.MERGE }, targetEntity = FileTableType.class, optional = false, fetch = FetchType.LAZY)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "fileid", referencedColumnName = "fileid", insertable = false, updatable = false)
	private FileTableType fileTableType;

	public FileTableType getFileTableType() {
		return fileTableType;
	}

	public void setFileTableType(FileTableType fileTableType) {
		this.fileTableType = fileTableType;
	}

	public int getFileId() {
		return fileId;
	}

	public void setFileId(int fileId) {
		this.fileId = fileId;
	}

	@Column(name = "content", columnDefinition = "TEXT")
	@org.hibernate.annotations.Type(type = "text")
	@Lob
	@XmlElement
	protected String content;

	/**
	 * Gets the value of the contentId property.
	 * 
	 */
	public int getContentId() {
		return contentId;
	}

	/**
	 * Sets the value of the contentId property.
	 * 
	 */
	public void setContentId(int value) {
		this.contentId = value;
	}

	/**
	 * Gets the value of the paraSeq property.
	 * 
	 */
	public int getParaSeq() {
		return paraSeq;
	}

	/**
	 * Sets the value of the paraSeq property.
	 * 
	 */
	public void setParaSeq(int value) {
		this.paraSeq = value;
	}

	/**
	 * Gets the value of the fileId property.
	 * 
	 */

	/**
	 * Gets the value of the content property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContent() {
		return content;
	}

	/**
	 * Sets the value of the content property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContent(String value) {
		this.content = value;
	}

	/*
	 * private FileTableType fileContent;
	 * 
	 * public FileTableType getFileContent() { return fileContent; }
	 * 
	 * public void setFileContent(FileTableType fileContent) { this.fileContent =
	 * fileContent; }
	 */
}
